#Part 1
library(RSQLite)
setwd('C:/Users/Brett/Downloads')
sqlite <- dbDriver("SQLite")
workingdb <- dbConnect(sqlite, "cunyweek9.sqlite")
dbListTables(workingdb)
I <- dbSendQuery(workingdb, "SELECT * FROM I")
Idf <- data.frame(fetch(I, -1))
II <- dbSendQuery(workingdb, "SELECT * FROM II")
IIdf <- data.frame(fetch(II, -1))
III <- dbSendQuery(workingdb, "SELECT * FROM III")
IIIdf <- data.frame(fetch(III, -1))
IV <- dbSendQuery(workingdb, "SELECT * FROM IV")
IVdf <- data.frame(fetch(IV, -1))
dbDisconnect(workingdb)
remove(sqlite)
remove(workingdb)
remove(I, II, III, IV)
par(mfrow=c(2,2))
plot(Idf, main="I")
abline(lm(Idf$y ~ Idf$x))
plot(IIdf, main="II")
abline(lm(IIdf$y ~ IIdf$x))
plot(IIIdf, main="III")
abline(lm(IIIdf$y ~ IIIdf$x))
plot(IVdf, main="IV")
abline(lm(IVdf$y ~ IVdf$x))

summary(Idf)
summary(IIdf)
summary(IIIdf)
summary(IVdf)

#Now let's make a more accurate predition model: (each lm makes 4 pictures)
par(mfrow=c(2,2))
Ilm <- lm(formula = y ~ x, data = Idf)
plot(Ilm)
#II
IIlm <- lm(formula = y ~ x, data = IIdf)
plot(IIlm)
#III
IIIlm <- lm(formula = y ~ x, data = IIIdf)
plot(IIIlm)
#IV
IVlm <- lm(formula = y ~ x, data = IVdf)
plot(IVlm)

anova(Ilm)
